"""empty message

Revision ID: 6134ece13ee2
Revises: 53b5a50c1e2e
Create Date: 2021-11-14 20:22:03.608422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6134ece13ee2'
down_revision = '53b5a50c1e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
