"""empty message

Revision ID: 7bdd4bf825b8
Revises: 1b6a1facc2f4
Create Date: 2021-11-14 20:29:59.106906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bdd4bf825b8'
down_revision = '1b6a1facc2f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
